# +++++ deoplete +++++ #
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
# +++++ ruby +++++ #
# railsプラグイン
[[plugins]]
repo = 'tpope/vim-rails'
# 補完
[[plugins]]
repo = 'takkii/Bignyanco'
# +++++ ruby +++++ #

# ++++++ python ++++++ #
# 補完
[[plugins]]
repo = 'zchee/deoplete-jedi'
# ++++++ python ++++++ #

# +++++ js +++++ #
[[plugins]]
repo = 'wokalski/autocomplete-flow'
# +++++ js +++++ #

# +++++ mathematica +++++ #
[[plugins]]
repo = 'voldikss/vim-mma'
# +++++ mathematica +++++ #

# +++++ vim +++++ #
[[plugins]]
repo = 'Shougo/neco-vim'
# +++++ vim +++++ #
