# +++++ coq +++++ #
[[plugins]]
repo = 'let-def/vimbufsync'
on_ft = 'coq'

[[plugins]]
repo = 'the-lambda-church/coquille'
on_ft = 'coq'
depends = ['vimbufsync']
hook_source = '''
  nmap <silent> <C-c><C-l> :CoqLaunch<CR>
  nmap <silent> <C-c><C-n> :CoqNext<CR>
  nmap <silent> <C-c><C-u> :CoqUndo<CR>
  nmap <silent> <C-c><C-c> :CoqToCursor<CR>
'''
# +++++ coq +++++ #

# +++++ rails +++++ #
[[plugins]]
repo = 'tpope/vim-rails'
# +++++ rails +++++ #

# +++++ html +++++  #
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-E>'
'''

[[plugins]]
repo = 'jvanja/vim-bootstrap4-snippets'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
# +++++ html +++++  #

# +++++ Julia +++++ #
[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  " If you have vim >=8.0 or Neovim >= 0.1.5
  if (has("termguicolors"))
  set termguicolors
  endif

  " For Neovim 0.1.3 and 0.1.4
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''
# +++++ Julia +++++ #

# mathematica
[[plugins]]
repo = 'rsmenon/vim-mathematica'
