# パッケージ管理
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# ファイルエクスプローラー
[[plugins]]
repo = 'scrooloose/nerdtree'

# gitterの表示
# [[plugins]]
# repo = 'airblade/vim-gitgutter'

# かっこ補完
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = 'let g:lexima_enable_basic_rules = 1'

# gtag
# [[plugins]]
# repo = 'jsfaint/gen_tags.vim'
# hook_add = 'g:gen_tags#gtags_default_map'

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = "let g:airline_powerline_fonts = 1"
hook_add = "set laststatus=2"

# indent 表示機能
[[plugins]]
repo = 'Yggdroot/indentLine'

# send terminal
[[plugins]]
repo = 'kkpmw/vim-sendtowindow'

# japanese
[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = '''
  let g:eskk#directory = "~/.eskk"
  let g:eskk#dictionary = { 'path': "~/.skk-jisyo", 'sorted': 0, 'encoding': 'utf-8', }
  let g:eskk#large_dictionary = { 'path': "~/.eskk/SKK-JISYO.L", 'sorted': 1, 'encoding': 'euc-jp', }
  let g:eskk#enable_completion = 1
  let g:eskk#server = {'host': 'localhost', 'port': 55100,}
'''

# 検索機能
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    map <Leader> <Plug>(easymotion-prefix)
    let g:EasyMotion_do_mapping = 0 " Disable default mappings

    " Jump to anywhere you want with minimal keystrokes, with just one key binding.
    " `s{char}{label}`
    " nmap s <Plug>(easymotion-overwin-f)
    " or
    " `s{char}{char}{label}`
    " Need one more keystroke, but on average, it may be more comfortable.
    nmap s <Plug>(easymotion-overwin-f2)

    " Turn on case insensitive feature
    let g:EasyMotion_smartcase = 1

    " JK motions: Line motions
    map <Leader>j <Plug>(easymotion-j)
    map <Leader>k <Plug>(easymotion-k)
'''

